matrix:
  include:
    - language: python
      python:
          - "3.5"
          - "3.9"

      install:
          - ./install-test.sh

      script:
          - ./runtests.sh

      after_success:
          - coveralls

    - language: cpp
      compiler:
          - gcc

      cache:
            apt: true

      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-multilib
          - g++-multilib
          - libncurses5-dev
          - libncurses5

      before_install:
          - echo 'getconf _NPROCESSORS_ONLN'
          - lsb_release -c
          - lsb_release -r

      script:
          - cd asmTests;./_tests.sh

      sudo: false
