matrix:
  include:
    - language: python
      python:
          - "3.9"

      install:
          - ./install-test.sh

      script:
          - ./runtests.sh

      after_success:
          - coveralls

    - language: cpp
      dist: focal
      compiler:
          - gcc

      cache:
            apt: true

      addons:
        apt:
          packages:
          - gcc-multilib
          - g++-multilib
          - libncurses5-dev:i386
          - libncurses5:i386

      before_install:
          - echo 'getconf _NPROCESSORS_ONLN'
          - lsb_release -c
          - lsb_release -r

      script:
          - ./_binarytests.sh

      sudo: false
