name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
           sudo apt-get update -y
           sudo apt-get install -y git make gcc gcc-multilib g++-multilib libncurses5-dev:i386 libncurses5:i386
           
    - name: build
      run: |
             ./echo 'getconf _NPROCESSORS_ONLN'
             ./lsb_release -c
             ./lsb_release -r
             ./_binarytests.sh
