name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
           sudo dpkg --add-architecture i386
           sudo apt-get update -y
           sudo apt-get install -y git make gcc gcc-multilib g++-multilib libncurses-dev:i386 libncurses:i386
           
    - name: build
      run: |
             ./_binarytests.sh
